backend:
  name: github
  repo: RangerRhino23/Dahlke-Media
  branch: main # Change to master if your default branch is master

media_folder: "assets" 
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - file: "index.html" 
        label: "Home Page"
        name: "home"
        format: raw 
        fields:
          - {label: "Page Content", name: "body", widget: "markdown"}
